# -*- coding: utf-8 -*-
"""RPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqT3O7IRsAEJBidD-tFKVly3hgvXAWKl
"""

import random

def computerChoice():
    choices = ['rock', 'paper', 'scissors']
    return random.choice(choices)

def determine_winner(userChoice, computerChoice):
    if userChoice == computerChoice:
        return "tie"
    elif (userChoice == 'rock' and computerChoice == 'scissors') or \
         (userChoice == 'paper' and computerChoice == 'rock') or \
         (userChoice == 'scissors' and computerChoice == 'paper'):
        return "win"
    else:
        return "lose"

def play_round():
    user_choice = input("Enter rock, paper, or scissors (or type 'exit' to quit): ").lower()
    if user_choice == 'exit':
        return 'exit', None
    if user_choice not in ['rock', 'paper', 'scissors']:
        print("Invalid choice. Please choose rock, paper, or scissors.")
        return None, None

    computer_choice = computerChoice()
    print(f"Computer chose: {computer_choice}")

    result = determine_winner(user_choice, computer_choice)
    return result, computer_choice

def againComp():
  choices = ['yes','no']
  return random.choice(choices)

def tas_kagit_makas_Gorkem_Aran():
    while True:
        user_score = 0
        computer_score = 0

        while user_score < 2 and computer_score < 2:
            print("\nNew Round!")
            result, computer_choice = play_round()
            if result == 'exit':
                print("Where are you going coward ?")
                return
            if result is None:
                continue

            if result == "win":
                user_score += 1
                print(f"How lucky you are. You won this round! Score - You: {user_score}, Computer: {computer_score}")
            elif result == "lose":
                computer_score += 1
                print(f"You lost this round. Score - You: {user_score}, Computer: {computer_score}")
            else:
                print(f"This round is a tie. Score - You: {user_score}, Computer: {computer_score}")

        if user_score == 2:
            print("\nCongratulations! You won the game!")
        else:
            print("\nSorry, I won the game! as I said I always win hahaha")
        again_Comp = againComp()
        play_again = input("Do you want to play again? (yes/no): ").lower()
        print("Computer's decide: ", again_Comp)
        if play_again != 'yes' or again_Comp != 'yes':
            print("Thank you for playing!")
            break

if __name__ == "__main__":
  welcome = "Hello !\nWelcome to the game that called Rock Paper Scissors. You know the rules but i want to recall for you.\n\nRock beats Scissors\nScissors beats Paper\nPaper beats Rock"
  print(welcome)
  tas_kagit_makas_Gorkem_Aran()